site_name: DBMS
nav:
- Home:
  - cheatsheet.md
  - index.md
- week3:
  - week3/tutorial_3_5.md
  - week3/Lecture 3.5 - Advanced SQL_annotated.md
  - week3/Lecture 3.3 - Intermediate SQL2_annotated.md
  - week3/Lecture 3.1 - SQL Examples_annotated.md
  - week3/Lecture 3.2 - Intermediate SQL1_annotated.md
  - week3/Lecture 3.4 - Intermediate SQL3_annotated.md
  - week3/week3.md
- Week 5:
  - Week 5/Lecture 5.4 - Relational Database Design4.md
  - Week 5/Lecture 5.1 - Relational Database Design1.md
  - Week 5/Lecture 5.2 - Relational Database Design2.md
  - Week 5/ex_can.md
  - Week 5/closureofartibut.md
  - Week 5/Lecture 5.5 - Relational Database Design5.md
  - Week 5/Lecture 5.3 - Relational Database Design3.md
  - Week 5/week5.md
- week1:
  - week1/Lecture 1.1 - Course Overview.md
  - week1/Lecture 1.3 - Why DBMS2.md
  - week1/week1.md
  - week1/textbook.md
  - week1/Lecture 1.4 - Intro to DBMS1.md
  - week1/summary.md
  - week1/Lecture 1.2 - Why DBMS1.md
  - week1/Lecture 1.5 - Intro to DBMS2.md
- week2:
  - week2/Lecture 2.2 - Introduction to Relational Model2.md
  - week2/tutorial_2.1.md
  - week2/week2.md
  - week2/Lecture 2.1 - Introduction to Relational Model1.md
  - week2/check_list.md
  - week2/Lecture 2.5 - Introduction to SQL3.md
  - week2/Lecture 2.4 - Introduction to SQL2.md
  - week2/Lecture 2.3 - Introduction to SQL1.md
- week4:
  - week4/Lecture 4.5 - Entity-Relationship Model3_annotated.md
  - week4/week4.md
  - week4/Lecture 4.2 - Formal Relational Query Languages2_annotated.md
  - week4/Lecture 4.1 - Formal Relational Query Languages1_annotated.md
  - week4/Lecture 4.3 - Entity-Relationship Model1_annotated.md
  - week4/Lecture 4.4 - Entity-Relationship Model2_annotated.md
site_author: PK
site_description: DESCRIPTION
repo_name: pk1308/DBMS
repo_url: https://github.com/pk1308/DBMS
theme:
  name: dracula
  features:
  - navigation.tabs
  - navigation.sections
  - toc.integrate
  - navigation.top
  language: en
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: teal
    accent: purple
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
    primary: teal
    accent: lime
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/pk1308
extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
- attr_list
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- admonition
- pymdownx.arithmatex:
    generic: true
- footnotes
- pymdownx.details
- pymdownx.superfences
- pymdownx.mark
- pymdownx.pathconverter
plugins:
- search
- mkdocs-pdf
copyright: '&copy; 2024 <a href="https://github.com/pk1308"  target="_blank" rel="noopener">PK</a>'
